### ISSUE TITLE
Fix drift in Azi

### ISSUE THREAD

**Issue by fnivek** [uf-mil/PropaGator#23]
You wrote this in my notes. I'm putting it in the issues to remind you.

**Comment by jpanikulam** [comment]
Does this ref #9 ?

**Comment by fnivek** [comment]
Is this the same issue Zach?

**Comment by zachgoins** [comment]
Don't believe it is the same issue. The visualizer was showing it going straight but it still drifted a bit to the left.

**Comment by jpanikulam** [comment]
The visualizer is using the raw B matrix assembled [here](https://github.com/uf-mil/PropaGator/blob/master/azi_drive/src/azimuth_drive/azimuth_drive.py#L97). 

- If it's drifting to the left when the visualizer thinks it is going straight, I *suspect* that is because the left and right thrusters are generating different thrust for the same value.

- If it is spinning when it supposed to be strafing, it is likely because the center of mass is offset from the geometric center of the boat, and Azi should (but doesn't) account for that. The simulator uses the geometric center, not the real COM. 

Could either of these explain it, @zachgoins ?
